# https://docs.netlify.com/configure-builds/file-based-configuration/
# https://community.netlify.com/t/using-pnpm-and-pnpm-workspaces/2759

[build]
	base = "/"
	publish = "dest"
	command = "npm run build"
	skip_processing = true

[build.environment]
	NPM_FLAGS="--prefix=/dev/null"

[[redirects]]
	from = "https://o137-timer.netlify.app/*"
	to = "https://timer.o137.dev/:splat"
	status = 301
	force = true
